plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  es2020: true
  node: true

extends:
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
