env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: 
  no-console: off, import/extensions: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
